export const SESSION = {
  LOGIN: "LOGIN",
  SUCCESS: "LOGIN_SUCCESS",
  ERROR: "LOGIN_ERROR",
  REQUESTED: "SESSION_REQUESTED",
  LOGOUT: "LOGOUT",
  EXIT: "LOGOUT_SUCCES"
}

export const DATA = {
  REQUESTED: "DATA_REQUESTED",
  LOADED: "DATA_LOADED",
  ADD_STORE: "ADD_STORE",
  ADD_DB: "ADD_DB",
  DELETE_STORE: "DELETE_STORE",
  DELETE_DB: "DELETE_DB",
  INVALID_DATA: "INVALID_DATA",
  ERROR: "ERROR_DB"
}