export const SESSION = {
  LOGIN: "LOGIN",
  SUCCESS: "LOGIN_SUCCESS",
  ERROR: "LOGIN_ERROR",
  REQUESTED: "SESSION_REQUESTED",
  LOGOUT: "LOGOUT",
  EXIT: "LOGOUT_SUCCES"
}

export const DATA = {
  REQUESTED: "DATA_REQUESTED",
  ORDERS_LOADED: "ORDERS_LOADED",
  ORDERLINE_LOADED: "ORDERLINE_LOADED",
  ADD_ORDERLINE_STORE: "ADD_ORDERLINE_STORE",
  ADD_ORDERLINE_DB: "ADD_ORDERLINE_DB",
  ADD_ORDER_STORE: "ADD_ORDER_STORE",
  ADD_ORDER_DB: "ADD_ORDER_DB",
  DELETE_STORE: "DELETE_STORE",
  DELETE_DB: "DELETE_DB",
  INVALID_DATA: "INVALID_DATA",
  ERROR: "ERROR_DB"
}